# Generated by Django 4.2 on 2023-04-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact_add', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField(max_length=300)),
            ],
        ),
    ]
