# Generated by Django 4.2 on 2023-04-06 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('supermarket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.category')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionReports',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customers')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.shoppingorder')),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.payment')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.products')),
            ],
        ),
    ]
