# Generated by Django 4.2 on 2023-05-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('a', 'admin'), ('u', 'user')], default='u', max_length=1, null=True, verbose_name='نقش کاربری'),
        ),
    ]
